# Generated by Django 2.2.7 on 2019-11-19 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='membership', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level', models.IntegerField(choices=[(0, 'Member'), (1, 'Plus'), (2, 'Premium'), (3, 'Professional'), (4, 'Instructor')])),
            ],
        ),
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('revised', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes'],
            },
        ),
    ]
