# Generated by Django 2.2.7 on 2019-11-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=45)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('revised', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=-100)),
            ],
            options={
                'ordering': ['-upvotes'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('Member', 'Member'), ('Plus', 'Plus'), ('Premium', 'Premium'), ('Professional', 'Professional'), ('Student', 'Student'), ('Instructor', 'Instructor')], default='Member', max_length=12),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='accounts.UserPrompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allprompts', to=settings.AUTH_USER_MODEL),
        ),
    ]
