# Generated by Django 2.2.7 on 2019-11-20 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_userprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Plus'), (2, 'Premium'), (3, 'Professional'), (4, 'Instructor')], default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='accounts.UserPrompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
