# Generated by Django 2.2.7 on 2019-11-21 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191120_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allprompts', to=settings.AUTH_USER_MODEL),
        ),
    ]
