# Generated by Django 2.2.7 on 2019-11-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191121_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Plus'), (2, 'Premium'), (3, 'Professional'), (4, 'Instructor')], default=0),
        ),
        migrations.AlterField(
            model_name='userprompt',
            name='upvotes',
            field=models.IntegerField(default=-100),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
