# Generated by Django 2.2.4 on 2019-10-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WriteBox',
        ),
    ]
