# Generated by Django 2.2.4 on 2019-10-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_writebox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='prompt',
        ),
        migrations.AddField(
            model_name='draft',
            name='prompt',
            field=models.CharField(default=str, max_length=300),
            preserve_default=False,
        ),
    ]
