# Generated by Django 2.2.4 on 2019-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191010_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='image',
            field=models.CharField(default='https://picsum.photos/seed/weed/1280/720', max_length=100),
            preserve_default=False,
        ),
    ]
