# Generated by Django 2.2.4 on 2019-10-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_draft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='text',
            field=models.TextField(max_length=1200),
        ),
    ]
