# Generated by Django 2.2.4 on 2019-10-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191023_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='text',
            field=models.TextField(max_length=1400),
        ),
    ]
