# Generated by Django 2.2.4 on 2019-10-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191024_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
