# Generated by Django 2.2.4 on 2019-10-26 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_draft_in_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=500)),
                ('progression', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('aural_quality', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('pov_clear', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('style_distinct', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('metaphors', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('setting_specfic', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('noun_specific', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('verb_specific', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('adjective_specific', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('worldview', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Somewhat')], max_length=1)),
                ('emi', models.CharField(choices=[('0', 'Indifferent'), ('1', 'Angry'), ('2', 'Disgusted'), ('3', 'Happy'), ('4', 'Sad'), ('5', 'Amused'), ('6', 'Surprised')], max_length=1)),
                ('favorite_lines', models.TextField(max_length=500)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Draft')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
