# Generated by Django 2.2.4 on 2019-10-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
