# Generated by Django 2.2.4 on 2019-11-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_feedback_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
