# Generated by Django 2.2.4 on 2019-11-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedback_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['revised']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-added']},
        ),
        migrations.AddField(
            model_name='draft',
            name='received_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allfeedback', to='core.Draft'),
        ),
    ]
