# Generated by Django 2.2.4 on 2019-11-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191108_0549'),
        ('core', '0013_auto_20191108_0848'),
    ]

    operations = [
    ]
