# Generated by Django 3.0 on 2019-12-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_draft_feedback_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='image',
            field=models.CharField(max_length=175),
        ),
    ]
