# Generated by Django 3.0 on 2019-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191216_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
