# Generated by Django 2.2.10 on 2020-03-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191216_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='emi',
            field=models.CharField(choices=[('0', 'Indifferent'), ('1', 'Angry'), ('2', 'Disgusted'), ('3', 'Happy'), ('4', 'Sad'), ('5', 'Amused'), ('6', 'Surprised'), ('7', 'Moved')], max_length=1),
        ),
    ]
